version: "3.7"
services:
  db:
    image: mysql:8
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password      
      
  backup:
    image: woolfg/mysql-backup-sidecar:${VERSION_TAG}
    volumes:
      - mysqldata:/var/lib/mysql
      - backup:/backup
    environment:
      CRON_SCHEDULE: "05 05 * * *"
      INCREMENTAL: "true"
      COMPRESS_THREADS: 1
      BACKUP_DIR: /backup
      DIR_DATE_PATTERN: "%Y%m%d"
      FULL_BACKUP_DATE_FORMAT: "%a"
      FULL_BACKUP_DATE_RESULT: "Sun"
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

volumes:
  mysqldata:
  backup:
    
secrets:
  db_password:
    file: db_secret
    